import type { Flyer } from './flyers'

/** Default flyer copy — expanded for full letter-size print. */
export const defaultFlyerEntries: Flyer[] = [
  {
    id: 'overview',
    slug: 'overview',
    title: "DOUG FORD'S ONTARIO",
    subtitle: "WHAT'S BEING SOLD OFF?",
    intro:
      'Ontario is shifting public money, land, water, and environmental protections toward private profit — while accountability is weakened. That includes rolling back freedom-of-information access and overriding evidence-based street safety policy. This flyer summarizes the pattern documented in public accounts, legislation, and independent reporting. Share it. Print it. Talk about it with neighbours.',
    heroImageUrl: '',
    highlights: [
      'Public $ → private delivery',
      'Greenbelt & waterfront opened up',
      'Bills 5, 60 & weakened oversight',
      'FOI rollback · street safety',
    ],
    sections: [
      {
        title: 'Healthcare',
        lead: 'Hospitals are stretched while for-profit operators and staffing agencies capture more of the budget.',
        bullets: [
          'Ontario has spent billions on private staffing agencies while public hospitals report deficits and staffing gaps.',
          'For-profit clinics have been paid more per procedure than public hospitals for the same surgeries (documented in CBC and Public Accounts reporting).',
          'Bill 124 capped wages for many public healthcare workers while agency rates climbed — in a workforce that is mostly women.',
          'Emergency departments and hallway medicine remain widespread as capacity shifts out of public hands.',
          'Long-term care bed allocations have favoured for-profit operators in multiple rounds of licensing.',
        ],
      },
      {
        title: 'Water & wastewater',
        lead: 'Bill 60 changes who controls the systems communities depend on every day.',
        bullets: [
          'Legislation opens pathways for corporate involvement in water and wastewater services.',
          'Municipal utilities face pressure to partner with or sell assets to private operators.',
          'Ratepayers risk losing transparency when decisions move behind corporate walls.',
          'Environmental enforcement and local accountability become harder when ownership changes.',
        ],
      },
      {
        title: 'Public land',
        lead: 'Protected land and public waterfront are treated as development opportunity — not a public trust.',
        bullets: [
          'Greenbelt land swaps removed protections while benefiting selected landowners and developers.',
          'Ontario Place privatization hands a major public waterfront to a private spa resort project.',
          'Farmland, watershed, and urban green space face ongoing pressure from sprawl and infrastructure.',
          'Communities often learn about deals after key decisions are already made.',
        ],
      },
      {
        title: 'Environment & Indigenous rights',
        lead: 'Species protection, public participation, and treaty obligations are being sidelined for faster development.',
        bullets: [
          'Bill 5 weakens species-at-risk rules and Indigenous participation in environmental decisions.',
          'Special economic zones can bypass normal environmental review.',
          'Ring of Fire and northern development proceed without adequate free, prior, and informed consent.',
          'Biodiversity loss and treaty violations carry long-term costs communities will bear.',
        ],
      },
    ],
    calloutTitle: '',
    calloutBody: '',
    published: true,
  },
  {
    id: 'water',
    slug: 'water',
    title: 'WATER & WASTEWATER',
    subtitle: 'WHO CONTROLS THE TAP?',
    intro:
      'Clean water and wastewater treatment are basic public responsibilities. Bill 60 and related provincial policy open the door to corporate control — weakening municipal oversight and making it harder for communities to hold decision-makers accountable.',
    heroImageUrl: '',
    highlights: ['Bill 60', 'Municipal utilities at risk', 'Rates & secrecy'],
    sections: [
      {
        title: 'What Bill 60 changes',
        lead: 'The "Your Health Act" and related water legislation are not only about healthcare — they reshape who can own and operate water services.',
        bullets: [
          'New frameworks allow greater private-sector involvement in water and wastewater services.',
          'Municipalities may face pressure to enter public-private partnerships or sell utility assets.',
          'Long-term contracts can lock communities in before full costs and risks are understood.',
          'Environmental compliance and spill response may be harder to enforce under private operators.',
          'Once privatized, bringing services back under public control is expensive and politically difficult.',
        ],
      },
      {
        title: 'What privatization costs communities',
        lead: 'Experience in Ontario and elsewhere shows the public still pays — often more — when profits are extracted.',
        bullets: [
          'Private operators must return profit to shareholders; that money comes from ratepayers or service cuts.',
          'Rate increases often follow privatization despite promises of "efficiency."',
          'Transparency declines when financial decisions happen behind corporate walls.',
          'Local councils lose leverage when multi-decade contracts bind future councils.',
          'Water security during climate emergencies requires public accountability — not quarterly earnings targets.',
        ],
      },
      {
        title: 'Questions to ask locally',
        lead: 'Use these at council meetings, with your MPP, and in local media.',
        bullets: [
          'Who owns our water and wastewater systems today — and who is lobbying to change that?',
          'What are the full 20-year costs of any proposed partnership vs public operation?',
          'What happens to rates, jobs, and environmental enforcement if a private operator fails?',
          'Will the public get open-book audits and council votes before any asset transfer?',
          'Does this align with municipal climate and watershed protection plans?',
        ],
      },
    ],
    calloutTitle: '',
    calloutBody: '',
    published: true,
  },
  {
    id: 'public-land',
    slug: 'public-land',
    title: 'PUBLIC LAND',
    subtitle: 'GREENBELT · ONTARIO PLACE · WHO BENEFITS?',
    intro:
      'Protected farmland, Greenbelt land, and public waterfront are being opened for development — often after opaque processes that benefit well-connected landowners and developers more than communities.',
    heroImageUrl: '',
    highlights: ['Greenbelt swaps', 'Ontario Place spa deal', 'Developer access'],
    sections: [
      {
        title: 'Greenbelt scandal',
        lead: 'The Auditor General and RCMP investigations documented land-use changes that favoured specific properties.',
        bullets: [
          'Provincial land swaps removed Greenbelt protections from selected parcels while adding elsewhere.',
          'Some landowners benefited from re-zoning and access decisions shortly before public announcements.',
          'Farmland and watershed protection were traded for sprawl-friendly development patterns.',
          'The Greenbelt was created to be permanent — political reversals undermine trust in all conservation policy.',
          'Communities were not given meaningful input before boundaries were redrawn.',
        ],
      },
      {
        title: 'Ontario Place & waterfront',
        lead: 'A public cultural and recreational waterfront is being handed to a private Austrian spa operator.',
        bullets: [
          'Ontario Place privatization replaces public access and cultural space with a commercial thermal spa.',
          'The footprint and public benefit of the original Ontario Place vision have been sharply reduced.',
          'Waterfront land in Toronto belongs to the public — not a single term of government.',
          'Similar patterns appear wherever public land is "leased" to private operators for decades.',
          'Ask: who profits, who pays maintenance costs, and what public access remains?',
        ],
      },
      {
        title: 'Sprawl & accountability',
        lead: 'When land rules change in favour of developers, housing affordability and climate targets suffer.',
        bullets: [
          'Opening protected land encourages car-dependent sprawl instead of infill and transit-oriented growth.',
          'Infrastructure costs for sprawl are borne by municipalities and provincial taxpayers.',
          'Backroom land deals are difficult to challenge without public records and journalism.',
          'ProtectOnt.ca/receipts tracks timelines and documented connections — verify and share.',
        ],
      },
    ],
    calloutTitle: '',
    calloutBody: '',
    published: true,
  },
  {
    id: 'wildlife',
    slug: 'wildlife',
    title: 'WILDLIFE & SPECIES',
    subtitle: 'BILL 5 · WEAKER PROTECTION',
    intro:
      'Bill 5 and related changes roll back species-at-risk protections, environmental assessment, and public participation — clearing the way for development that communities and scientists have long opposed.',
    heroImageUrl: '',
    highlights: ['Bill 5', 'Species at risk', 'SEZs'],
    sections: [
      {
        title: 'Bill 5 — what changed',
        lead: 'Ontario Nature, the David Suzuki Foundation, and legal experts have documented broad rollbacks.',
        bullets: [
          'Species-at-risk habitat protections weakened — more projects can proceed with less scrutiny.',
          'Environmental assessment requirements reduced for categories of development.',
          'Public participation windows shortened; community objections are easier to dismiss.',
          'Ministerial discretion expanded — fewer independent checks on harmful projects.',
          'Petitions calling for repeal reflect widespread concern across Ontario communities.',
        ],
      },
      {
        title: 'Special economic zones',
        lead: 'SEZs can bundle land-use, environmental, and labour rules into fast-track development packages.',
        bullets: [
          'Special economic zones may bypass normal municipal and environmental planning.',
          'Water, wildlife habitat, and farmland in zone boundaries face concentrated risk.',
          'Jobs promises are often overstated; environmental liabilities stay with the public.',
          'Once a zone is declared, local democratic control is permanently reduced.',
        ],
      },
      {
        title: 'Why biodiversity matters here',
        lead: 'Ontario\'s species and ecosystems underpin farming, fishing, tourism, and climate resilience.',
        bullets: [
          'Habitat loss is irreversible on human timescales — extinction is permanent.',
          'Weakened enforcement shifts costs to future generations and rural communities.',
          'Indigenous knowledge and stewardship are sidelined when participation rules shrink.',
          'Full issue page: protectont.ca/wildlife',
        ],
      },
    ],
    calloutTitle: '',
    calloutBody: '',
    published: true,
  },
  {
    id: 'indigenous-rights',
    slug: 'indigenous-rights',
    title: 'INDIGENOUS RIGHTS',
    subtitle: 'CONSENT · TREATIES · RING OF FIRE',
    intro:
      'Free, prior, and informed consent is not optional — it is a treaty obligation and a human rights standard. Provincial policy is pushing Ring of Fire and other northern development without adequate consent processes or respect for Indigenous governance.',
    heroImageUrl: '',
    highlights: ['FPIC', 'Ring of Fire', 'Bill 5'],
    sections: [
      {
        title: 'Free, prior & informed consent',
        lead: 'UNDRIP and Canadian law increasingly recognize FPIC — Ontario\'s rush to develop often ignores it.',
        bullets: [
          'Bill 5 reduces Indigenous participation in environmental decision-making.',
          'Major projects proceed before consent is sought from affected Nations.',
          'Treaty rights to hunt, fish, and govern traditional territories are treated as obstacles.',
          'Court challenges and land defender actions reflect legitimate opposition — not "blockades" to dismiss.',
          'Reconciliation requires changing process, not just adding consultation after decisions are made.',
        ],
      },
      {
        title: 'Ring of Fire',
        lead: 'A massive mining and infrastructure corridor in the James Bay lowlands affects multiple First Nations.',
        bullets: [
          'Roads, power lines, and mines would permanently alter wetlands and caribou habitat.',
          'Promised jobs and revenue rarely match environmental and cultural costs borne locally.',
          'Nations have not uniformly consented — some have explicitly opposed the current timeline.',
          'Federal and provincial governments have pressured acceleration despite outstanding land claims.',
          'Water contamination risk in northern river systems affects downstream communities for generations.',
        ],
      },
      {
        title: 'What solidarity looks like',
        lead: 'Non-Indigenous Ontarians can support Nations leading on their own terms.',
        bullets: [
          'Listen to Indigenous-led organizations — do not speak over them.',
          'Contact your MPP: development without consent is not reconciliation.',
          'Learn treaty history for the land you live on.',
          'Read more: protectont.ca/indigenous-rights',
        ],
      },
    ],
    calloutTitle: '',
    calloutBody: '',
    published: true,
  },
  {
    id: 'accountability',
    slug: 'accountability',
    title: 'ACCOUNTABILITY',
    subtitle: 'FOLLOW THE PUBLIC MONEY',
    intro:
      'When services are privatized and land deals happen behind closed doors, transparency is the first casualty. Protect Ontario pulls public accounts, legislation, and documented journalism into one place so citizens can see the pattern — and demand better.',
    heroImageUrl: '/products/yard-signs/ford-failed-you.png',
    highlights: ['Public Accounts', 'Auditor General', 'Open data'],
    sections: [
      {
        title: 'What the books show',
        lead: 'Ontario Public Accounts and Detailed Schedule of Payments reveal where provincial dollars actually go.',
        bullets: [
          'Spending on private staffing agencies, consultants, and contractors has grown in multiple sectors.',
          'Hospital and ministry deficits coexist with large transfers to private operators.',
          'Open data exists — but it is scattered across portals most residents never see.',
          'ProtectOnt.ca visualizes trends so you do not need a finance degree to spot shifts.',
        ],
      },
      {
        title: 'Legislation & oversight',
        lead: 'Bills that change ownership of water, land, and healthcare pass with limited debate time.',
        bullets: [
          'Omnibus bills bundle unrelated changes — making scrutiny harder for MPPs and the public.',
          'Bill 97 (2026) excludes premier and ministerial records from Ontario\'s Freedom of Information and Protection of Privacy Act (FIPPA), with retroactive effect — see protectont.ca/flyers/freedom-of-information.',
          'Auditor General reports on Greenbelt and other files documented process failures.',
          'Integrity Commissioner and lobbying registers exist but require journalists and citizens to connect dots.',
          'Weakened environmental and Indigenous participation rules reduce formal opposition channels.',
        ],
      },
      {
        title: 'How to use ProtectOnt.ca',
        lead: 'Built for neighbours, organizers, and journalists who want verified starting points.',
        bullets: [
          'Issue pages: healthcare, water, public land, wildlife, Indigenous rights.',
          'Methodology and data sources are documented — challenge us if we get it wrong.',
          'Protest calendar: protectont.ca/protests',
          'Contact your MPP with one click: protectont.ca/take-action',
          'Join the volunteer network: protectont.ca/join',
        ],
      },
    ],
    calloutTitle: '',
    calloutBody: '',
    published: true,
  },
  {
    id: 'freedom-of-information',
    slug: 'freedom-of-information',
    title: 'FREEDOM OF INFORMATION',
    subtitle: 'SHUTTING THE FILES',
    intro:
      'Ontario\'s freedom-of-information laws let residents, journalists, and researchers request government records. Bill 97 — passed in 2026 as part of the Plan to Protect Ontario Act — rolls back that right for the premier, cabinet ministers, and their political staff, and weakens oversight in other ways. Civil liberties groups and Ontario\'s Information and Privacy Commissioner warned these changes undermine transparency Ontarians have relied on for decades.',
    heroImageUrl: '',
    highlights: ['Bill 97 · FIPPA', 'Ministerial records exempt', 'Retroactive to 1988'],
    sections: [
      {
        title: 'What Bill 97 changes',
        lead: 'Source: Legislative Assembly of Ontario — Bill 97, Schedule 7 (FIPPA amendments); received Royal Assent in 2026.',
        bullets: [
          'FIPPA will no longer apply to records in the custody or control of a minister, a minister\'s office, or a parliamentary assistant — unless the same record is also held by a government institution.',
          'That exclusion covers the premier, every cabinet minister, parliamentary assistants, and their political staff — the offices where many high-stakes decisions are made.',
          'The standard deadline to answer an access request increases from 30 calendar days to 45 business days — a longer wait for public answers.',
          'Certain cybersecurity records prepared under the Enhancing Digital Security and Trust Act, 2024 are also carved out of access laws.',
        ],
      },
      {
        title: 'Retroactive secrecy',
        lead: 'Source: Bill 97 transitional provisions (Ontario.ca/ola); Canadian Civil Liberties Association analysis.',
        bullets: [
          'Ministerial-record exclusions are deemed to have come into force on January 1, 1988 — not just for future requests.',
          'Transitional rules can invalidate existing disclosure orders and court decisions that conflict with the new exclusions.',
          'Records that were already ordered released may be pulled back behind the new wall of secrecy.',
          'CCLA warned this lets the government avoid accountability for decisions already under scrutiny.',
        ],
      },
      {
        title: 'Why independent voices objected',
        lead: 'Source: Information and Privacy Commissioner of Ontario (ipc.on.ca), March 2026; CCLA (ccla.org).',
        bullets: [
          'The IPC said excluding the highest levels of government "diminish[es] the public\'s right to information" and that retroactivity "raises serious concerns."',
          'The Commissioner argued modernizing FOI should mean faster disclosure and proactive release — not rolling back rights.',
          'CCLA called the ministerial carve-out one of the most troubling elements of Bill 97 and warned cybersecurity exemptions could hide evaluations that pose no security risk.',
          'When ministers\' records leave FIPPA, statutory privacy and security safeguards for those records are weakened too — the IPC flagged increased cybersecurity risk.',
        ],
      },
      {
        title: 'Questions to ask locally',
        lead: 'Use this flyer at doors, community boards, and MPP offices.',
        bullets: [
          'Why hide ministerial records now — after Greenbelt, Ontario Place, and healthcare privatization debates?',
          'What requests or court orders does this retroactive change affect?',
          'Will your MPP vote to restore FIPPA coverage for ministerial offices?',
          'Ask for proactive disclosure of contracts, lobbying contacts, and land-use decisions — not less access.',
          'More context: protectont.ca/flyers/accountability · protectont.ca/take-action',
        ],
      },
    ],
    calloutTitle: '',
    calloutBody: '',
    published: true,
  },
  {
    id: 'public-care',
    slug: 'public-care',
    title: 'WHEN PUBLIC CARE IS CUT',
    subtitle: 'WOMEN PAY TWICE',
    intro:
      'Public services are how we share care — hospitals, schools, home care, and childcare. When those systems are underfunded or privatized, the cost does not vanish. It shifts onto workers (mostly women in feminized professions) and onto unpaid caregivers at home (also disproportionately women). This flyer summarizes the pattern with documented sources.',
    heroImageUrl: '',
    highlights: ['Bill 124 · feminized workforce', 'Agency $ · wage caps', 'Unpaid care at home'],
    sections: [
      {
        title: 'At work — feminized public-sector jobs',
        lead: 'Source: Statistics Canada — gender and health care occupations; Ontario e-Laws — Bill 124 (2019).',
        bullets: [
          'About nine in ten registered nurses in Canada are women (Statistics Canada, 2021).',
          'Personal support workers, early childhood educators, and many teachers in Ontario are also predominantly women.',
          'Bill 124 capped compensation increases for many broader-public-sector workers, including healthcare staff, while hospitals spent billions on private staffing agencies.',
          'Agency workers often cost far more per hour than equivalent public employees — public money flowing to intermediaries instead of stable public jobs.',
          'Underpaying and understaffing feminized care work is a policy choice, not an accident.',
        ],
      },
      {
        title: 'At home — when public care shrinks',
        lead: 'Source: Canadian Centre for Policy Alternatives; Broadbent Institute — care economy research.',
        bullets: [
          'Longer ER waits, home-care waitlists, and reduced school supports push care back onto families.',
          'Unpaid caregiving — for children, parents, and disabled family members — falls disproportionately on women.',
          'Single-parent and multigenerational households bear the heaviest load when public capacity is cut.',
          'Two-tier healthcare pressure hits women twice: longer waits for care, and more unpaid work filling the gap.',
          'Investing in public capacity is how we share care instead of privatizing it onto households.',
        ],
      },
      {
        title: 'In the movement — volunteer organizing',
        lead: 'Grassroots opposition across Ontario relies on unpaid coordination — signs, events, mutual aid, and turnout.',
        bullets: [
          'Much of Ford-era organizing is volunteer-heavy: local Facebook groups, school councils, health coalitions, and protest marshals.',
          'Women often coordinate this invisible work even when men are the public speakers.',
          'Credit union and paid staff organizers too — this is not “only women care,” but the load is gendered.',
          'Public accountability needs both street presence and the behind-the-scenes labour that makes it possible.',
          'Join the network: protectont.ca/join · Find events: protectont.ca/protests',
        ],
      },
      {
        title: 'What to ask for',
        lead: 'Use this flyer at doors, community boards, and MPP offices.',
        bullets: [
          'Reinvest in public hospitals and reduce reliance on for-profit agencies.',
          'Repeal or fully remedy Bill 124’s harm to health and education workers.',
          'Expand public home care, childcare, and school supports — not two-tier shortcuts.',
          'Ask your MPP: who benefits when public care is cut, and who pays the price at home?',
          'More: protectont.ca/healthcare#shared-care · protectont.ca/take-action',
        ],
      },
    ],
    calloutTitle: '',
    calloutBody: '',
    published: true,
  },
  {
    id: 'bike-lanes-safety',
    slug: 'bike-lanes-safety',
    title: 'BIKE LANES & SPEED CAMERAS',
    subtitle: 'SAFETY CUTS · LAWSUIT SHIELDS',
    intro:
      'The Ford government has overridden Toronto on protected bike lanes, banned municipal automated speed enforcement cameras province-wide, and passed legislation that blocks lawsuits when those changes hurt people. A Superior Court judge found the targeted Toronto bike-lane removals arbitrary — they would not reduce congestion and would put cyclists at greater risk — yet the province appealed. These are shallow populist moves that sacrifice road safety for drivers-first messaging.',
    heroImageUrl: '',
    highlights: ['Bill 212 · Toronto lanes', 'Bill 56 · speed cameras', 'Lawsuit immunity'],
    sections: [
      {
        title: 'Toronto bike lanes — Bill 212',
        lead: 'Source: Bill 212, Reducing Gridlock, Saving You Time Act, 2024 (ola.org); Cycle Toronto et al. v. Attorney General of Ontario, 2025 ONSC 4397.',
        bullets: [
          'Bill 212 amended the Highway Traffic Act to require removal of protected bike lanes on Bloor Street, University Avenue, and Yonge Street in Toronto — restoring motor-vehicle lanes.',
          'A last-minute amendment added ss. 195.10–195.14: no lawsuits against the government, municipalities, or contractors for collisions, injuries, or deaths resulting from removing those lanes.',
          'In July 2025, Justice Schabas ruled s. 195.6 unconstitutional: removal would increase harm to cyclists without achieving the stated goal of reducing congestion.',
          'The judge found the law arbitrary and grossly disproportionate under Section 7 of the Charter; internal advice to government had already said removals would not fix gridlock.',
          'The province appealed; a Court of Appeal hearing was held in January 2026 — decision pending as of print date.',
        ],
      },
      {
        title: 'Speed cameras — Bill 56',
        lead: 'Source: Bill 56, Building a More Competitive Economy Act, 2025 (ola.org); CBC and Global News reporting, November 2025.',
        bullets: [
          'Bill 56 repealed Part XIV.1 of the Highway Traffic Act — ending municipal automated speed enforcement (ASE) cameras in school zones and community safety zones.',
          'Royal Assent November 3, 2025; municipalities were required to remove cameras by November 14, 2025 — before permanent traffic-calming replacements were in place.',
          'Premier Ford called the cameras a "tax grab"; police associations and many municipalities had documented their effectiveness at slowing drivers.',
          'Section 206.6 extinguishes certain lawsuits against the Crown and municipalities tied to repealing speed-camera contracts.',
          'Temporary signage was promised, but ripping out working enforcement first trades proven safety tools for political optics.',
        ],
      },
      {
        title: 'Future bike lanes — Bill 60',
        lead: 'Source: Bill 60, Fighting Delays, Building Faster Act, 2025 (ola.org); Environmental Registry of Ontario notice 025-1071.',
        bullets: [
          'Bill 60 prohibits municipalities from reducing motor-vehicle lanes when installing new bicycle lanes — unless a regulation exempts the project.',
          'Passed November 24, 2025; Ottawa and other cities reported planned bike projects cancelled or redesigned because of the lane-reduction ban.',
          'The province says cities can still build bike lanes that do not remove a car lane — but on many arterial roads, safe separated lanes require rebalancing space.',
          'Bill 60 stacks on Bill 212: remove existing protected infrastructure in Toronto, then restrict how other cities build safer alternatives.',
          'This does not fix induced demand — more car lanes tend to fill with more cars, not less congestion.',
        ],
      },
      {
        title: 'What this means for commuters',
        lead: 'Pedestrians, cyclists, children, and low-income residents who rely on bikes bear the highest risk.',
        bullets: [
          'Protected bike lanes separate people from traffic — removing them increases injury and death risk, according to the court record and city data cited in Cycle Toronto v. AG.',
          'Speed cameras enforce limits 24/7 in school zones; removing them shifts enforcement back to sporadic police presence.',
          'Lawsuit-immunity clauses signal the government expects harm — then blocks accountability.',
          'Congestion is a regional problem; scapegoating bike lanes ignores transit, induced demand, and sprawl policy.',
          'Talk to neighbours: protectont.ca/flyers · protectont.ca/protests · protectont.ca/take-action',
        ],
      },
    ],
    calloutTitle: '',
    calloutBody: '',
    published: true,
  },
  {
    id: 'ontario-place',
    slug: 'ontario-place',
    title: 'ONTARIO PLACE',
    subtitle: 'PUBLIC WATERFRONT · 95-YEAR PRIVATE LEASE',
    intro:
      'Ontario Place is provincially owned waterfront on Lake Ontario — not sold off, but leased to a private operator for generations. Unlike the reversed Greenbelt carve-out, this deal is still moving ahead: a commercial thermal spa and waterpark under a 95-year lease, with less public environmental scrutiny than similar-scale projects elsewhere.',
    heroImageUrl: '',
    highlights: ['95-year Therme lease', 'Bill 5 · less EBR scrutiny', 'Still moving ahead'],
    sections: [
      {
        title: 'What is being proposed',
        lead: 'Source: Ontario.ca final designs; CTV News on Ontario Place designs (2025).',
        bullets: [
          'Ontario Place remains provincially owned waterfront — public land handed to Therme Canada under a 95-year lease.',
          'Therme would operate a large thermal spa and waterpark with paid day passes on a site many Torontonians treat as public waterfront.',
          'The province promotes rebuilt free parkland on the West Island — beaches, trails, and open space — alongside the commercial complex.',
          'A 2025 redesign roughly halved the spa footprint and lowered building heights; critics say the core lease structure is unchanged.',
          'A generation-long private hold is hard to take back — far longer than most political cycles or council terms.',
        ],
      },
      {
        title: 'Bill 5 and the Environmental Bill of Rights',
        lead: 'Source: Legislative Assembly of Ontario — Bill 5 (ola.org).',
        bullets: [
          'Ontario Place redevelopment is carved out from normal Environmental Bill of Rights participation requirements.',
          'Residents get less notice and less recourse than for comparably large projects elsewhere in the province.',
          'Bill 5 stacks with the lease model: streamline first, consult later — the same playbook critics tie to the Greenbelt scandal.',
          'Weakened public participation makes it harder to challenge harms before construction locks in.',
          'More on Bill 5 rollbacks: protectont.ca/wildlife · protectont.ca/public-land',
        ],
      },
      {
        title: 'Why this fight matters now',
        lead: 'Unlike the Greenbelt, this deal has not been reversed — it is one of the most consequential live fights over public land in Ontario.',
        bullets: [
          'Public pressure reversed the Greenbelt carve-out in 2023; whether the same happens here depends on waterfront organizing.',
          'Critics argue the public gets less waterfront control and less recourse than the scale of the project deserves.',
          'Jobs and tourism talking points do not replace democratic accountability on public commons.',
          'Waterfront land in Toronto belongs to the public — not a single term of government.',
          'Full background: protectont.ca/public-land#ontario-place',
        ],
      },
      {
        title: 'Questions to ask locally',
        lead: 'Use at community boards, council meetings, and MPP offices.',
        bullets: [
          'Who profits from a 95-year lease — and who pays maintenance and environmental costs?',
          'What public access and cultural programming is guaranteed in writing for the full lease term?',
          'Why exempt Ontario Place from normal Environmental Bill of Rights scrutiny?',
          'Will your MPP support pausing the lease until independent public review is complete?',
          'Take action: protectont.ca/take-action · protectont.ca/protests',
        ],
      },
    ],
    calloutTitle: '',
    calloutBody: '',
    published: true,
  },
  {
    id: 'ring-of-fire',
    slug: 'ring-of-fire',
    title: 'RING OF FIRE',
    subtitle: 'SPECIAL ECONOMIC ZONES · BILL 5',
    intro:
      'Bill 5 creates "special economic zones" where trusted proponents and designated projects can be exempt from environmental and municipal rules that normally apply. The first zone was declared in the Ring of Fire — peatlands and rivers on Treaty 9 territory where several First Nations have not consented to development at the pace or scale proposed.',
    heroImageUrl: '',
    highlights: ['Bill 5 SEZ Act', 'Treaty 9 territory', 'Mining & roads'],
    sections: [
      {
        title: 'Special economic zones — what changed',
        lead: 'Source: Legislative Assembly of Ontario — Bill 5 (ola.org); CBC on Ring of Fire SEZ (2025).',
        bullets: [
          'Bill 5\'s Special Economic Zones Act lets the province designate areas where projects can bypass rules that normally apply — including environmental and municipal requirements.',
          'The first special economic zone was declared in the Ring of Fire, a region of peatlands and rivers on Treaty 9 territory.',
          'SEZs are not empty land — they are home territories, traplines, burial sites, and watersheds.',
          'Once a zone is declared, local democratic control and standard environmental review are permanently weakened.',
          'Ontario Nature and the David Suzuki Foundation have called for repeal of Bill 5\'s environmental rollbacks.',
        ],
      },
      {
        title: 'Ring of Fire development',
        lead: 'Source: CBC; The Canadian Encyclopedia — Ring of Fire; Bill 5 Mining Act amendments.',
        bullets: [
          'The Ring of Fire is promoted as a critical minerals hub — roads, power lines, and mines across the Far North.',
          'Building infrastructure affects water flowing south, caribou habitat, and communities that depend on both.',
          'Bill 5 changes the Mining Act to prioritize protecting "Ontario\'s economy" and to speed approvals.',
          'The Crown has a legal duty to consult when Indigenous rights may be affected — consultation is not the same as consent.',
          'Several First Nations have not consented to development at the current pace or scale.',
        ],
      },
      {
        title: 'Treaty rights and accountability',
        lead: 'Source: UN Declaration on the Rights of Indigenous Peoples (UNDRIP); Ontario\'s Action Plan on UNDRIP.',
        bullets: [
          'Free, prior, and informed consent is a treaty obligation and human rights standard — not optional consultation after decisions are made.',
          'Bill 5 extinguishes certain causes of action — limiting communities\' ability to seek redress when harmed.',
          'Weakened species protection under Bill 5 compounds risks to caribou, wetlands, and northern river systems.',
          'Water contamination risk in peatland watersheds affects downstream communities for generations.',
          'Full background: protectont.ca/indigenous-rights · protectont.ca/wildlife',
        ],
      },
      {
        title: 'What you can do',
        lead: 'Stand with Indigenous nations leading on their own terms.',
        bullets: [
          'Contact your MPP: demand repeal of Bill 5 and an end to special economic zones without consent.',
          'Listen to and share statements from affected First Nations — follow their leadership, not provincial talking points.',
          'Support indigenous-led environmental monitoring and treaty education in your community.',
          'Join rallies where Indigenous nations and allies are making the demand visible: protectont.ca/protests',
          'More: protectont.ca/take-action · protectont.ca/flyers/indigenous-rights',
        ],
      },
    ],
    calloutTitle: '',
    calloutBody: '',
    published: true,
  },
]
